server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://localhost:4200"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
      routes:
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/cliente/**,/venta/**,/carrito_venta/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: tecnico-service
          uri: lb://tecnico-service
          predicates:
            - Path=/soporte_tecnico/**,/reparacion/**
        - id: compra-service
          uri: lb://compra-service
          predicates:
            - Path=/proveedor/**,/compra/**,/carrito_compra/**
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/producto/**,/categoria/**