server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
           allowedOrigins: "https://localhost:4200"
           allowedMethods:
           - GET
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/cliente/**,/venta/**,/carrito_venta/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: tecnico-service
          uri: lb://tecnico-service
          predicates:
            - Path=/soporte_tecnico/**,/reparacion/**
        - id: compra-service
          uri: lb://compra-service
          predicates:
            - Path=/proveedor/**,/compra/**,/carrito_compra/**
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/producto/**,/categoria/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/tutorial-realm
            authorization-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/token
        registration:
          tutorial-client:
            provider: keycloak
            client-id: tutorial-client
            client-secret: LUyT6VWyXG5qWpD9XQzhVNEFUP2s07mr
            authorization-grant-type: authorization_code
            //redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-client"