server:
  port: 8081
spring:
  cloud:     
    config:
      server:
        git:
          default-label: zip
          uri: https://github.com/PieroCahuanaPalomino/RegistroCompraVentas.git
          search-paths: config-data
  application:
    name: config-service